import torch

EMBEDDING_SIZE = 300
HIDDEN_SIZE = 256
LEARNING_RATE = 0.01
EPOCHS = 100
MINI_BATCH_SIZE = 512
DEVICE_CUDA = 'cuda'
DEVICE_CPU = 'cpu'
CHECKPOINT_DIR = "../checkpoints/rnn_pytorch/"
CHECKPOINT_PATH = None
DEVICE = device = torch.device(DEVICE_CUDA if torch.cuda.is_available() else DEVICE_CPU)
CHECKPOINT_FREQ = 50
MIN_LOSS_IMPROVEMENT = 0.0001
BEST_LOSS = float('inf')
STACK_LENGTH = 4
L2_LAMBDA = 0.01
STACK_LENGTH = 4
SEQ_LENGTH = 5
